version: "3.9"
services:

  # docker run -d \
  # --name postgres_container \
  # -e POSTGRES_USER=root \
  # -e POSTGRES_PASSWORD=root \
  # -e POSTGRES_DB=jobhunter \
  # -p 5010:5010 \
  # --restart always \
  # postgres

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"