CREATE TABLE "contacts" (
  "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" varchar NOT NULL,
  "Phone" varchar NOT NULL,
  "Email" varchar NOT NULL,
  "Address" varchar NOT NULL,
  "Category" varchar NOT NULL,
  "CreatedAt" timestamp DEFAULT (now())
);

CREATE TABLE "categories" (
  "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ContactId" bigint UNIQUE,
  "Label" varchar NOT NULL,
  "CreatedAt" timestamp DEFAULT (now())
);

CREATE INDEX ON "contacts" ("Name");

CREATE INDEX ON "contacts" ("Email");

CREATE INDEX ON "contacts" ("Category");

CREATE INDEX ON "contacts" ("Name", "Email", "Category");

CREATE INDEX ON "categories" ("Id");

ALTER TABLE "contacts" ADD FOREIGN KEY ("Id") REFERENCES "categories" ("ContactId");
