CREATE TABLE "categories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "label" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "contacts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "phone" varchar NOT NULL,
  "email" varchar NOT NULL,
  "address" varchar NOT NULL,
  "category_id" BIGINT NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  FOREIGN KEY ("category_id") REFERENCES "categories" ("id")
);

CREATE INDEX ON "contacts" ("name");
CREATE INDEX ON "contacts" ("email");
CREATE INDEX ON "contacts" ("category_id");
CREATE INDEX ON "contacts" ("name", "email", "category_id");
